title: Make // Andy // Make
description: I muck about with electronics and try to succeed at life
author: Andy Warburton
github: https://github.com/agusmakmun
about: I muck about with electronics and try to succeed at life <a href="https://ko-fi.com/andyw">Buy me a coffee!</a>
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/andywarburton.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/awarburton"
    - icon: fa-github
      link: "https://github.com/andywarburton"
    - icon: fa-instagram
      link: "https://instagram.com/awarburton"  

share:
  twitter_username: awarburton
  #fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
#   - text: My Projects
#   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://makeandymake.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
